import { Inter } from 'next/font/google'
import './globals.css'
import './style.scss'
import Navbar from './navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-gray-50 dark:bg-gray-900'>
      <body className="bg-gray-50 dark:bg-gray-900">
        <Navbar />
        {children}</body>
    </html>
  )
}
