import { Inter } from 'next/font/google'
import './globals.css'
import './style.scss'
import Navbar from './navbar/Navbar'
import { getServerSession } from 'next-auth'
import AuthProvider from './__util/SessionProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en" >
      <body >
        <AuthProvider session={session}>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
